---
title: "Waffle House Index"
author: "NICAR 2020"
date: "3/6/2020"
output:
  flexdashboard::flex_dashboard:
    theme: paper
    source_code: embed
---


```{r setup, include=FALSE}
# setting up R Markdown options

# We want to hide the code and only see the results
knitr::opts_chunk$set(echo = F)

# We don't want to see any warnings from our code
knitr::opts_chunk$set(warning = F)

# We don't want to see any messages
knitr::opts_chunk$set(message = F)
```

```{r install_packages}
# You must have the flexdashboard package installed
# Before knitting this R Markdown file
# install.packages("flexdashboard")

# This function checks if you don't have the correct packages installed yet
# If not, it will install it for you
packages <- c("tidyverse", "flexdashboard",
              "crosstalk", "leaflet", "DT")

if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())), repos = "http://cran.us.r-project.org")  
}
library(tidyverse)
library(flexdashboard)
library(crosstalk)  
library(leaflet)   
library(DT) 
```

```{r load_and_clean_data}
sheet <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRrObtIYokP-AywK_A33uF2phYvbBhi-lZxNndqngrB9U2srj_1iWBlLdUWBKisjlUIAqZSSeEr1VXy/pub?output=csv")


st <- SharedData$new(sheet)
```

Waffle House Index {data-icon="ion-stats-bars"}
=====================================  

Column {data-width=200}
-------------------------------------

### Filters

```{r filter_section}
# What filters would you like to set up?
# Look at line 68 in 07_crosstalk_05.Rmd for ideas

```


Column {data-width=800}
-------------------------------------

### Datatable

```{r filterable_table}
# Customize how you want the datatable to look
# Line 104 for context

```


### Interactive map

```{r interactive_map}
# map! You'll have to use the custom crosstalk object but
# you can recycle your options from 02_your_turn.R
# Also check out line 152 in 07_crosstalk_05.Rmd
```
