#### Loading packages --------

# This function checks if you don't have the correct packages installed yet
# If not, it will install it for you
packages <- c("sf", "tidyverse", "tigris",
              "tidycensus", "mapdeck")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())), repos = "http://cran.us.r-project.org")  
}
library(sf)
library(tidyverse)
library(tigris)
library(tidycensus)
library(mapdeck)

#### Loading Census block population data by race in Louisiana ---

acs <- readRDS("data/acs_geoid.RDS")

# Ucomment the lines of code below to run download the
# data yourself

#census_key <- "YourCensusKeyGoesHere"

## this function downloads the data by variables we've set
#acs <- get_acs("block group", table = "B02001", cache_table = TRUE,
#               geometry = TRUE, state = "22",
#               year = 2016, output = "tidy")

## These lines cleans up the downloaded data frame
#acs <- acs %>%
#  mutate(
#    id = str_extract(variable, "[0-9]{3}$") %>% as.integer
#  ) %>%
  # variable 1 is the "total", which is just the sum of the others
#  filter(id > 1 & id < 8) %>%
#  mutate(race =case_when(
#    id == 2 ~ "White",
#    id == 3 ~ "Black",
#    id == 4 ~ "Native",
#    id == 5 | id == 6 ~ "Asian",
#    id == 7 ~ "Other"
#  )) %>% 
#  group_by(GEOID, race) %>% 
#  summarise(estimate = sum(estimate))

glimpse(acs)

#### Quickly plot the data --------

# let's look at one variable so it doesn't throw off the map
acs_black <- acs %>%
  filter(race=="Black")

glimpse(acs_black)

mb_key <- "PutYourKeyHere"

mapdeck(token = mb_key, style = mapdeck_style("dark")) %>%
  add_polygon(
    data = acs_black,
    fill_colour = "estimate",
    fill_opacity = .4
  )

#### Sampling --------

points <- readRDS("data/points_exported.RDS")

glimpse(points)

## Only run these lines of code if you have a lot of free time
## You can adjust the number of dots generated by 
## dividing the estimate below (in this instance the denominator is 100)
## 

#generate_samples <- function(data) 
#  suppressMessages(st_sample(data, size = round(data$estimate / 100)))


#points <- map(acs_split, generate_samples)
#points <- imap(points, 
#               ~st_sf(data_frame(race = rep(.y, length(.x))),
#                      geometry = .x))

#points <- do.call(rbind, points)

#points <- points %>% group_by(race) %>% summarise()

points %>% mutate(n_points = map_int(geometry, nrow))

#### Dot density map time ----

# setting up a color palette

m <- grDevices::colorRamp(c("aquamarine2", "dodgerblue2", "orange", "gray", "firebrick3"))(1:256/256)

mapdeck(token = mb_key, 
        style = 'mapbox://styles/mapbox/dark-v9',
        zoom = 6,
        location = c(-92.394604, 31.091401)) %>% 
  add_scatterplot(
    data=points,
    radius=1,
    fill_opacity=.3,
    fill_colour = "race",
    palette = m,
    layer_id = "scatter_layer",
    update_view= FALSE,
    #, tooltip = "race"
    legend=T
  )
