---
title: "Crosstalk 1"
author: "NICAR 2020"
date: "3/5/2020"
output:
  flexdashboard::flex_dashboard:
    theme: paper
    source_code: embed
---

```{r setup, include=FALSE}
# setting up R Markdown options

# We want to hide the code and only see the results
knitr::opts_chunk$set(echo = F)

# We don't want to see any warnings from our code
knitr::opts_chunk$set(warning = F)

# We don't want to see any messages
knitr::opts_chunk$set(message = F)
```

```{r install_packages}
# You must have the flexdashboard package installed
# Before knitting this R Markdown file
# install.packages("flexdashboard")

# This function checks if you don't have the correct packages installed yet
# If not, it will install it for you
packages <- c("tidyverse", "flexdashboard",
              "crosstalk", "leaflet", "DT")

if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())), repos = "http://cran.us.r-project.org")  
}
library(tidyverse)
library(flexdashboard)
library(crosstalk)  
library(leaflet)   
library(DT)   
```

Opioids in State {data-icon="ion-stats-bars"}
=====================================  

Column {data-width=200}
-------------------------------------

### Filters

```{r filter_section}
print("Filter stuff goes here")
```


Column {data-width=800}
-------------------------------------

### Datatable

```{r filterable_table}
print("Filterable table goes here")
```

### Interactive map

```{r interactive_map}
print("Interactive map goes here")
```

